# Étape 1: Construction de l'application Angular
FROM node:18 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer toutes les dépendances (y compris les devDependencies)
RUN npm install 

# Copier le reste des fichiers
COPY . .

# Construire l'application Angular en mode production
RUN npm run build --prod

# Étape 2: Utiliser une image Node.js pour servir l'application Angular avec Express
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers construits d'Angular et le serveur Express
COPY --from=build /app/dist /app/dist
COPY --from=build /app/server.js /app/server.js
COPY --from=build /app/package*.json /app/

# Installer les dépendances de production pour Express
RUN npm install --only=production

# Exposer le port 8080 pour accéder à l'application
EXPOSE 8080

# Lancer le serveur Express pour servir l'application Angular
CMD ["node", "server.js"]