services:
  karangue-backend:   # ← ici on renomme 'app' en 'karangue-backend'
    build:
      context: .
      dockerfile: Dockerfile
    image: niassy1903/karangue-backend:latest  # ← ajouter cette ligne
    container_name: karangue-backend_app
    restart: "no"
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - karangue-backend_network


  redis:
    image: redis:latest
    container_name: karangue-backend_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - karangue-backend_network

networks:
  karangue-backend_network:
    driver: bridge
