# Étape 1 : Utiliser une image de Node.js pour le backend
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
# Installer production deps avec peer legacy
RUN npm install 


# Copier le reste des fichiers de l'application connexion-rfid
COPY . .

# Exposer le port utilisé par l'API connexion-rfid
EXPOSE 3002

# Lancer l'API connexion-rfid
CMD ["node", "server.js"]
